name: 'Linter code'

on: 
  pull_request:
    branches:
      - master
jobs:
  install-node-modules-and-linter:
    name: Install node modules
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: Linter code
        run: npm run lint
    